In [5]:
import os

In [6]:
import pandas as pd

trips_2017_Q1 = pd.read_csv('Trips_2017_Q1.csv')
trips_2017_Q2 = pd.read_csv('Trips_2017_Q2.csv')
trips_2017_Q3 = pd.read_csv('Trips_2017_Q3.csv')
trips_2017_Q4 = pd.read_csv('Trips_2017_Q4.csv')

In [7]:
trips_2017 = pd.concat([trips_2017_Q1, trips_2017_Q2, trips_2017_Q3, trips_2017_Q4])

In [8]:
trips_2017.sample(20)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
220312,16474640,9/17/2017 13:18:59,9/17/2017 13:28:43,4599,584,29,Noble St & Milwaukee Ave,16,Paulina Ave & North Ave,Subscriber,Male,1989.0
26936,14822119,6/29/2017 10:30:03,6/29/2017 10:33:47,4361,224,87,Racine Ave & Fullerton Ave,87,Racine Ave & Fullerton Ave,Customer,NaN,NaN
337702,14461786,6/10/2017 15:47:25,6/10/2017 15:52:58,3992,333,59,Wabash Ave & Roosevelt Rd,2,Buckingham Fountain,Customer,NaN,NaN
741959,13980287,5/13/2017 10:21:48,5/13/2017 10:42:12,3320,1224,264,Stetson Ave & South Water St,118,Sedgwick St & North Ave,Subscriber,Male,1967.0
436983,16219216,9/3/2017 19:07:25,9/3/2017 19:30:01,908,1356,4,Burnham Harbor,341,Adler Planetarium,Customer,NaN,NaN
542357,16882446,10/9/2017 18:11,10/9/2017 18:23,6030,674,35,Streeter Dr & Grand Ave,3,Shedd Aquarium,Subscriber,Male,1979.0
574065,16846975,10/7/2017 23:38,10/7/2017 23:51,1761,781,327,Sheffield Ave & Webster Ave,27,Larrabee St & North Ave,Subscriber,Male,1991.0
527555,16114356,8/29/2017 16:31:41,8/29/2017 16:35:16,5311,215,14,Morgan St & 18th St,274,Racine Ave & 15th St,Subscriber,Male,1989.0
1101201,13541586,4/4/2017 07:08:49,4/4/2017 07:16:10,5330,441,195,Columbus Dr & Randolph St,91,Clinton St & Washington Blvd,Subscriber,Male,1991.0
1007923,13654339,4/15/2017 11:55:08,4/15/2017 12:03:22,422,494,370,Calumet Ave & 21st St,255,Indiana Ave & Roosevelt Rd,Subscriber,Female,1989.0
252498,13212003,2/15/2017 17:10:35,2/15/2017 17:15:35,1456,300,405,Wentworth Ave & 35th St,279,Halsted St & 35th St (*),Subscriber,Male,1988.0
449954,16204755,9/3/2017 11:56:42,9/3/2017 12:15:40,1005,1138,244,Ravenswood Ave & Irving Park Rd,117,Wilton Ave & Belmont Ave,Customer,NaN,NaN
271168,17207901,11/7/2017 13:36,11/7/2017 13:43,580,426,140,Dearborn Pkwy & Delaware Pl,289,Wells St & Concord Ln,Subscriber,Male,1982.0
648070,15973574,8/22/2017 15:43:34,8/22/2017 15:54:52,4882,678,115,Sheffield Ave & Wellington Ave,93,Sheffield Ave & Willow St,Subscriber,Female,1991.0
380397,16286760,9/7/2017 16:05:06,9/7/2017 16:25:36,2571,1230,341,Adler Planetarium,35,Streeter Dr & Grand Ave,Customer,NaN,NaN
252307,16438808,9/15/2017 16:13:32,9/15/2017 16:17:46,4153,254,14,Morgan St & 18th St,129,Blue Island Ave & 18th St,Subscriber,Male,1979.0
70111,17449046,12/9/2017 15:56,12/9/2017 16:00,6038,234,148,State St & 33rd St,272,Indiana Ave & 31st St,Subscriber,Male,1998.0
339832,14459415,6/10/2017 14:26:19,6/10/2017 14:38:34,1664,735,3,Shedd Aquarium,76,Lake Shore Dr & Monroe St,Customer,NaN,NaN
146744,17358871,11/28/2017 17:18,11/28/2017 17:26,5216,462,91,Clinton St & Washington Blvd,44,State St & Randolph St,Subscriber,Male,1969.0
396256,14393614,6/7/2017 12:37:37,6/7/2017 13:01:59,249,1462,264,Stetson Ave & South Water St,125,Rush St & Hubbard St,Customer,NaN,NaN

In [9]:
trips_2017['birthyear'] = trips_2017['birthyear'].fillna(-1).astype(int)

In [10]:
trips_2017.sample(20)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
1380970,15116998,7/13/2017 16:32:44,7/13/2017 16:43:45,158,661,195,Columbus Dr & Randolph St,77,Clinton St & Madison St,Subscriber,Male,1986
182059,17316171,11/22/2017 5:45,11/22/2017 5:52,5438,408,43,Michigan Ave & Washington St,98,LaSalle St & Washington St,Subscriber,Male,1958
650052,16756184,10/2/2017 13:27,10/2/2017 13:57,2224,1812,333,Ashland Ave & Blackhawk St,53,LaSalle (Wells) St & Huron St,Subscriber,Male,1992
113442,14722151,6/24/2017 11:43:42,6/24/2017 13:05:28,1675,4906,34,Cannon Dr & Fullerton Ave,34,Cannon Dr & Fullerton Ave,Customer,NaN,-1
508613,16136824,8/30/2017 17:17:19,8/30/2017 17:21:33,6036,254,198,Green St & Madison St,77,Clinton St & Madison St,Subscriber,Male,1986
589583,14165838,5/26/2017 09:42:23,5/26/2017 09:47:23,5210,300,130,Damen Ave & Division St,128,Damen Ave & Chicago Ave,Subscriber,Male,1987
167562,16536975,9/20/2017 17:29:18,9/20/2017 17:36:31,3817,433,184,State St & 35th St,402,Shields Ave & 31st St,Subscriber,Female,1991
376146,14417687,6/8/2017 15:51:43,6/8/2017 16:00:48,5766,545,51,Clark St & Randolph St,88,Racine Ave & Randolph St,Customer,NaN,-1
1336849,15167614,7/15/2017 18:03:49,7/15/2017 18:11:01,5405,432,181,LaSalle St & Illinois St,110,Dearborn St & Erie St,Customer,NaN,-1
1197770,15329608,7/23/2017 19:27:57,7/23/2017 19:35:26,2816,449,451,Sheridan Rd & Loyola Ave,449,Clark St & Columbia Ave,Subscriber,Female,1982
1425630,15063698,7/10/2017 17:11:39,7/10/2017 17:19:36,5772,477,81,Daley Center Plaza,110,Dearborn St & Erie St,Subscriber,Female,1986
135127,14697466,6/22/2017 22:39:15,6/22/2017 22:49:35,4643,620,301,Clark St & Schiller St,313,Lakeview Ave & Fullerton Pkwy,Subscriber,Male,1993
275033,13184048,2/11/2017 12:15:45,2/11/2017 12:44:34,5139,1729,291,Wells St & Evergreen Ave,236,Sedgwick St & Schiller St,Subscriber,Male,1988
331766,14468438,6/10/2017 20:29:48,6/10/2017 20:49:27,1927,1179,255,Indiana Ave & Roosevelt Rd,112,Green St & Randolph St,Subscriber,Female,1987
741882,13980367,5/13/2017 10:27:56,5/13/2017 10:29:33,994,97,301,Clark St & Schiller St,291,Wells St & Evergreen Ave,Subscriber,Male,1984
284195,16400567,9/13/2017 17:42:47,9/13/2017 17:57:18,1387,871,177,Theater on the Lake,303,Broadway & Cornelia Ave,Subscriber,Female,1992
71510,16648727,9/26/2017 15:00:42,9/26/2017 15:17:55,5872,1033,203,Western Ave & 21st St,214,Damen Ave & Grand Ave,Subscriber,Male,1979
1112751,15430757,7/28/2017 13:56:49,7/28/2017 14:27:44,4272,1855,126,Clark St & North Ave,85,Michigan Ave & Oak St,Customer,NaN,-1
431746,14349850,6/5/2017 08:22:50,6/5/2017 08:37:41,4010,891,75,Clinton St & Jackson Blvd,51,Clark St & Randolph St,Subscriber,Male,1964
785560,13925717,5/8/2017 19:33:32,5/8/2017 19:43:11,2707,579,263,Rhodes Ave & 32nd St,148,State St & 33rd St,Subscriber,Female,1990

In [12]:
trips_2017['start_time'] = pd.to_datetime(trips_2017['start_time']).dt.strftime('%m/%d/%Y %H:%M:%S')
trips_2017['end_time'] = pd.to_datetime(trips_2017['end_time']).dt.strftime('%m/%d/%Y %H:%M:%S')

In [13]:
trips_2017.sample(10)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
465983,16186487,09/02/2017 11:49:31,09/02/2017 12:07:12,6206,1061,6,Dusable Harbor,341,Adler Planetarium,Customer,NaN,-1
31438,13479539,03/25/2017 11:06:39,03/25/2017 11:30:40,5676,1441,172,Rush St & Cedar St,94,Clark St & Armitage Ave,Customer,NaN,-1
159722,16545934,09/21/2017 08:14:38,09/21/2017 08:43:15,6264,1717,527,Western Ave & Howard St,326,Clark St & Leland Ave,Subscriber,Male,1989
125165,17383646,12/01/2017 06:10:00,12/01/2017 06:13:00,2519,188,76,Lake Shore Dr & Monroe St,6,Dusable Harbor,Subscriber,Male,1967
930543,15642548,08/07/2017 12:24:07,08/07/2017 12:40:00,2986,953,34,Cannon Dr & Fullerton Ave,296,Broadway & Belmont Ave,Customer,NaN,-1
397200,17055778,10/21/2017 15:50:00,10/21/2017 16:07:00,3286,1025,459,Lakefront Trail & Bryn Mawr Ave,458,Broadway & Thorndale Ave,Customer,NaN,-1
739953,13982514,05/13/2017 12:11:25,05/13/2017 12:40:03,1556,1718,107,Desplaines St & Jackson Blvd,414,Canal St & Taylor St,Customer,NaN,-1
1517550,14958010,07/05/2017 16:53:49,07/05/2017 16:56:17,3887,148,133,Kingsbury St & Kinzie St,56,Desplaines St & Kinzie St,Subscriber,Male,1977
291383,13163788,02/07/2017 18:08:38,02/07/2017 18:21:53,5106,795,128,Damen Ave & Chicago Ave,510,Spaulding Ave & Division St,Subscriber,Male,1983
643003,16764234,10/02/2017 18:38:00,10/02/2017 18:40:00,3913,144,243,Lincoln Ave & Leavitt St,316,Damen Ave & Sunnyside Ave,Subscriber,Female,1987

Now I will save the new table as csv, this will be openned and processed using SQL 
in MySQL.

In [14]:
trips_2017.to_csv('trips_2017.csv', index=False)