In [3]:
import pandas as pd

trips_2016_Q1 = pd.read_csv('Trips_2016_Q1.csv')

In [4]:
trips_2016_Q1.sample(20)

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
24856,9048029,3/28/2016 17:37,3/28/2016 17:44,4336,441,199,Wabash Ave & Grand Ave,31,Franklin St & Chicago Ave,Subscriber,Female,1985.0
192787,8829418,2/28/2016 15:17,2/28/2016 15:42,2659,1498,76,Lake Shore Dr & Monroe St,197,Michigan Ave & Madison St,Customer,NaN,NaN
239146,8769717,2/19/2016 14:02,2/19/2016 14:28,1622,1530,338,Calumet Ave & 18th St,76,Lake Shore Dr & Monroe St,Customer,NaN,NaN
139205,8900179,3/9/2016 18:59,3/9/2016 19:12,1637,733,38,Clark St & Lake St,80,Aberdeen St & Monroe St,Subscriber,Male,1991.0
301467,8681268,2/1/2016 14:29,2/1/2016 14:45,2598,957,2,Michigan Ave & Balbo Ave,97,Museum Campus,Customer,NaN,NaN
133249,8907804,3/10/2016 17:04,3/10/2016 17:19,2023,858,18,Wacker Dr & Washington St,291,Wells St & Evergreen Ave,Subscriber,Female,1986.0
73021,8984610,3/20/2016 15:29,3/20/2016 15:35,2,362,185,Stave St & Armitage Ave,69,Damen Ave & Pierce Ave,Subscriber,Male,1992.0
360145,8599580,1/14/2016 16:44,1/14/2016 16:50,2478,374,212,Orleans St & Ohio St,66,Clinton St & Lake St,Subscriber,Male,1983.0
33947,9035933,3/27/2016 10:59,3/27/2016 11:03,4016,252,232,Pine Grove Ave & Waveland Ave,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1974.0
147686,8889473,3/8/2016 19:33,3/8/2016 19:37,1620,231,127,Lincoln Ave & Fullerton Ave,144,Larrabee St & Webster Ave,Subscriber,Female,1988.0
30371,9040389,3/27/2016 16:32,3/27/2016 16:52,3151,1188,6,Dusable Harbor,2,Michigan Ave & Balbo Ave,Customer,NaN,NaN
63330,8997314,3/22/2016 7:50,3/22/2016 7:55,1895,319,43,Michigan Ave & Washington St,164,Franklin St & Lake St,Subscriber,Male,1966.0
243761,8763706,2/18/2016 17:05,2/18/2016 17:15,2036,611,31,Franklin St & Chicago Ave,52,Michigan Ave & Lake St,Subscriber,Male,1982.0
186420,8837791,2/29/2016 19:15,2/29/2016 19:19,991,277,337,Clark St & Chicago Ave,176,Clark St & Elm St,Subscriber,Female,1986.0
195238,8826613,2/28/2016 12:02,2/28/2016 12:10,2874,510,194,Wabash Ave & Wacker Pl,195,Columbus Dr & Randolph St,Customer,NaN,NaN
371278,8582513,1/9/2016 11:35,1/9/2016 11:50,2809,913,133,Kingsbury St & Kinzie St,33,State St & Van Buren St,Subscriber,Male,1959.0
259413,8740132,2/12/2016 17:05,2/12/2016 17:12,2526,430,32,Racine Ave & Congress Pkwy,129,Blue Island Ave & 18th St,Subscriber,Male,1978.0
20673,9053289,3/29/2016 9:31,3/29/2016 9:44,1723,761,364,Larrabee St & Oak St,211,St. Clair St & Erie St,Subscriber,Male,1965.0
282633,8707059,2/5/2016 18:06,2/5/2016 18:10,2582,228,114,Sheffield Ave & Addison St,303,Broadway & Cornelia Ave,Subscriber,Male,1984.0
95753,8955561,3/16/2016 20:32,3/16/2016 20:44,3147,700,223,Clifton Ave & Armitage Ave,220,Hampden Ct & Diversey Pkwy,Subscriber,Female,1995.0

In [5]:
# First I see what data type this column is, 
# I had problems in Mysql when trying to upload the data

column = trips_2016_Q1['birthyear']
type_counts = column.apply(lambda x: type(x).__name__).value_counts()

In [6]:
print(type_counts)

float    396913

Name: birthyear, dtype: int64

In [7]:
#trips_2016['birthyear'] = trips_2016['birthyear'].fillna(-1).astype(int)
#trips_2016.sample(10)

#Now I will merge the tables so I have single tables per year, making analysis easier

In [8]:
# I add the missing tables

apr_2016 = pd.read_csv('Trips_2016_apr.csv')
may_2016 = pd.read_csv('Trips_2016_may.csv')
jun_2016 = pd.read_csv('Trips_2016_jun.csv')
q3_2016 = pd.read_csv('Trips_2016_Q3.csv')
q4_2016 = pd.read_csv('Trips_2016_Q4.csv')

Then I add all of the raw tables together to see if there are no problems between them

In [9]:
incomplete_2016 = pd.concat([apr_2016, may_2016, jun_2016, q3_2016, q4_2016])

In [10]:
incomplete_2016.sample(20)

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
498489,12370442,10/16/2016 18:31:57,10/16/2016 19:01:30,3322,1773,59,Wabash Ave & Roosevelt Rd,268,Lake Shore Dr & North Blvd,Subscriber,Male,1986.0
422618,12461727,10/23/2016 12:18:05,10/23/2016 12:36:51,3909,1126,253,Clifton Ave & Lawrence Ave,296,Broadway & Belmont Ave,Subscriber,Male,1954.0
601990,12248274,10/8/2016 12:20:39,10/8/2016 12:45:55,1844,1516,196,Cityfront Plaza Dr & Pioneer Ct,177,Theater on the Lake,Customer,NaN,NaN
116849,10284778,6/24/2016 7:23,6/24/2016 7:32,1211,551,337,Clark St & Chicago Ave,98,LaSalle St & Washington St,Subscriber,Male,1984.0
259181,12652835,11/7/2016 07:50:59,11/7/2016 08:12:47,3213,1308,288,Larrabee St & Armitage Ave,100,Orleans St & Merchandise Mart Plaza,Subscriber,Female,1951.0
64207,12072805,9/25/2016 13:31:27,9/25/2016 13:54:46,1505,1399,130,Damen Ave & Division St,71,Morgan St & Lake St,Subscriber,Male,1975.0
227052,10150188,6/17/2016 12:18,6/17/2016 12:34,3870,951,328,Ellis Ave & 58th St,355,South Shore Dr & 67th St,Subscriber,Female,1973.0
200242,10181943,6/18/2016 17:29,6/18/2016 17:38,5787,534,255,Indiana Ave & Roosevelt Rd,341,Adler Planetarium,Customer,NaN,NaN
524785,12339515,10/14/2016 14:28:26,10/14/2016 14:49:43,1218,1277,3,Shedd Aquarium,90,Millennium Park,Customer,NaN,NaN
570,9378472,4/30/2016 11:35,4/30/2016 12:23,1945,2930,304,Broadway & Waveland Ave,35,Streeter Dr & Grand Ave,Customer,NaN,NaN
647208,12194401,10/4/2016 16:52:44,10/4/2016 17:07:06,97,862,91,Clinton St & Washington Blvd,60,Dayton St & North Ave,Subscriber,Male,1983.0
182333,12743942,11/15/2016 12:08:51,11/15/2016 12:22:54,3346,843,194,Wabash Ave & Wacker Pl,182,Wells St & Elm St,Subscriber,Male,1981.0
337684,9413914,5/4/2016 7:58,5/4/2016 8:14,1436,1004,156,Clark St & Wellington Ave,48,Larrabee St & Kingsbury St,Subscriber,Female,1991.0
872792,11111551,8/3/2016 19:52:06,8/3/2016 20:42:30,1635,3025,486,Oakley Ave & Irving Park Rd,486,Oakley Ave & Irving Park Rd,Customer,NaN,NaN
199549,9594344,5/18/2016 16:53,5/18/2016 16:58,2059,329,327,Sheffield Ave & Webster Ave,224,Halsted St & Willow St,Subscriber,Female,1988.0
404730,11670995,9/3/2016 11:32:14,9/3/2016 12:01:56,5430,1782,26,McClurg Ct & Illinois St,126,Clark St & North Ave,Customer,NaN,NaN
366297,12528561,10/28/2016 20:05:45,10/28/2016 20:20:29,4626,884,342,Wolcott Ave & Polk St,75,Clinton St & Jackson Blvd,Subscriber,Male,1990.0
357860,9987330,6/8/2016 21:23,6/8/2016 21:29,5137,355,164,Franklin St & Lake St,48,Larrabee St & Kingsbury St,Subscriber,Male,1989.0
1244305,10665812,7/12/2016 15:35:42,7/12/2016 15:44:04,3742,502,283,LaSalle St & Jackson Blvd,133,Kingsbury St & Kinzie St,Subscriber,Male,1980.0
209269,9110685,4/5/2016 15:19,4/5/2016 15:26,3747,392,283,LaSalle St & Jackson Blvd,91,Clinton St & Washington Blvd,Subscriber,Female,1971.0

They were added correctly, afterwards I will clean the birthyear column with the code used 
previously.

In [11]:
incomplete_2016['birthyear'] = incomplete_2016['birthyear'].fillna(-1).astype(int)

In [12]:
incomplete_2016.sample(20)

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
36108,12928411,12/15/2016 18:34:54,12/15/2016 18:37:37,4650,163,117,Wilton Ave & Belmont Ave,299,Halsted St & Roscoe St,Subscriber,Male,1981
16419,10406642,6/30/2016 6:25,6/30/2016 6:26,7,64,5,State St & Harrison St,5,State St & Harrison St,Subscriber,Male,1995
308831,11784672,9/9/2016 08:45:33,9/9/2016 08:54:41,5836,549,414,Canal St & Taylor St,191,Canal St & Monroe St (*),Subscriber,Male,1982
76025,12059071,9/24/2016 16:10:35,9/24/2016 16:16:22,5653,347,2,Michigan Ave & Balbo Ave,59,Wabash Ave & Roosevelt Rd,Customer,NaN,-1
719663,11296726,8/13/2016 13:33:40,8/13/2016 13:48:20,2743,881,291,Wells St & Evergreen Ave,329,Lake Shore Dr & Diversey Pkwy,Subscriber,Male,1990
509767,11546675,8/27/2016 11:10:44,8/27/2016 11:21:22,4272,638,119,Ashland Ave & Lake St,130,Damen Ave & Division St,Subscriber,Male,1988
870674,11114178,8/3/2016 23:08:49,8/3/2016 23:16:32,3867,464,287,Franklin St & Monroe St,74,Kingsbury St & Erie St,Subscriber,Male,1993
82682,12866858,12/2/2016 15:19:10,12/2/2016 15:23:01,398,231,174,Canal St & Madison St,96,Desplaines St & Randolph St,Subscriber,Male,1966
120386,9689730,5/23/2016 20:41,5/23/2016 21:03,2376,1313,228,Damen Ave & Melrose Ave,463,Clark St & Berwyn Ave,Subscriber,Female,1989
162738,9173591,4/14/2016 8:17,4/14/2016 8:20,4361,178,36,Franklin St & Jackson Blvd,49,Dearborn St & Monroe St,Subscriber,Male,1979
475355,9839382,6/1/2016 13:33,6/1/2016 13:40,427,403,174,Canal St & Madison St,133,Kingsbury St & Kinzie St,Subscriber,Male,1978
90582,12042356,9/23/2016 17:19:08,9/23/2016 17:23:49,4564,281,197,Michigan Ave & Madison St,174,Canal St & Madison St,Subscriber,Male,1969
322002,9435429,5/5/2016 19:57,5/5/2016 20:17,1566,1208,44,State St & Randolph St,57,Clinton St & Roosevelt Rd,Subscriber,Female,1971
299495,12606809,11/4/2016 06:00:31,11/4/2016 06:12:32,5057,721,232,Pine Grove Ave & Waveland Ave,177,Theater on the Lake,Subscriber,Female,1991
18400,10404239,6/29/2016 20:41,6/29/2016 21:05,4027,1419,194,Wabash Ave & Wacker Pl,37,Dearborn St & Adams St,Customer,NaN,-1
43402,9321563,4/24/2016 18:48,4/24/2016 18:56,4234,467,183,Damen Ave & Augusta Blvd,61,Wood St & Milwaukee Ave,Subscriber,Male,1988
612631,12236161,10/7/2016 15:09:56,10/7/2016 15:15:47,4912,351,107,Desplaines St & Jackson Blvd,169,Canal St & Harrison St,Subscriber,Male,1952
164487,11955093,9/18/2016 17:17:11,9/18/2016 17:32:19,3514,908,464,Damen Ave & Foster Ave,459,Lakefront Trail & Bryn Mawr Ave,Subscriber,Female,1984
175584,10211760,6/20/2016 9:18,6/20/2016 9:44,3784,1546,177,Theater on the Lake,211,St. Clair St & Erie St,Subscriber,Male,1969
1313414,10582721,7/8/2016 17:59:24,7/8/2016 18:24:30,613,1507,224,Halsted St & Willow St,249,Montrose Harbor,Subscriber,Male,1977

In [13]:
trips_2016 = pd.concat([trips_2016_Q1, incomplete_2016])

I will change the date format too, to make it easier to work with later on

In [14]:
trips_2016.rename(columns={'starttime':'start_time', 'stoptime':'end_time'}, inplace=True)

In [15]:
trips_2016['start_time'] = pd.to_datetime(trips_2016['start_time']).dt.strftime('%m/%d/%Y %H:%M:%S')
trips_2016['end_time'] = pd.to_datetime(trips_2016['end_time']).dt.strftime('%m/%d/%Y %H:%M:%S')

In [16]:
trips_2016.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,9080551,03/31/2016 23:53:00,04/01/2016 00:07:00,155,841,344,Ravenswood Ave & Lawrence Ave,458,Broadway & Thorndale Ave,Subscriber,Male,1986.0
1,9080550,03/31/2016 23:46:00,03/31/2016 23:57:00,4831,649,128,Damen Ave & Chicago Ave,213,Leavitt St & North Ave,Subscriber,Male,1980.0
2,9080549,03/31/2016 23:42:00,03/31/2016 23:46:00,4232,210,350,Ashland Ave & Chicago Ave,210,Ashland Ave & Division St,Subscriber,Male,1979.0
3,9080548,03/31/2016 23:37:00,03/31/2016 23:55:00,3464,1045,303,Broadway & Cornelia Ave,458,Broadway & Thorndale Ave,Subscriber,Male,1980.0
4,9080547,03/31/2016 23:33:00,03/31/2016 23:37:00,1750,202,334,Lake Shore Dr & Belmont Ave,329,Lake Shore Dr & Diversey Pkwy,Subscriber,Male,1969.0

Now I will save the new table as csv, this will be openned and processed using SQL 
in MySQL.

In [17]:
trips_2016['birthyear'] = trips_2016['birthyear'].fillna(-1).astype(int)

In [22]:
trips_2016.head(30)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,9080551,03/31/2016 23:53:00,04/01/2016 00:07:00,155,841,344,Ravenswood Ave & Lawrence Ave,458,Broadway & Thorndale Ave,Subscriber,Male,1986
1,9080550,03/31/2016 23:46:00,03/31/2016 23:57:00,4831,649,128,Damen Ave & Chicago Ave,213,Leavitt St & North Ave,Subscriber,Male,1980
2,9080549,03/31/2016 23:42:00,03/31/2016 23:46:00,4232,210,350,Ashland Ave & Chicago Ave,210,Ashland Ave & Division St,Subscriber,Male,1979
3,9080548,03/31/2016 23:37:00,03/31/2016 23:55:00,3464,1045,303,Broadway & Cornelia Ave,458,Broadway & Thorndale Ave,Subscriber,Male,1980
4,9080547,03/31/2016 23:33:00,03/31/2016 23:37:00,1750,202,334,Lake Shore Dr & Belmont Ave,329,Lake Shore Dr & Diversey Pkwy,Subscriber,Male,1969
5,9080546,03/31/2016 23:31:00,03/31/2016 23:41:00,4302,638,67,Sheffield Ave & Fullerton Ave,304,Broadway & Waveland Ave,Subscriber,Male,1991
6,9080545,03/31/2016 23:30:00,03/31/2016 23:46:00,2295,926,156,Clark St & Wellington Ave,166,Ashland Ave & Wrightwood Ave,Subscriber,Male,1990
7,9080544,03/31/2016 23:30:00,03/31/2016 23:41:00,4303,637,200,MLK Jr Dr & 47th St,411,Halsted St & 47th Pl,Subscriber,Male,1964
8,9080543,03/31/2016 23:25:00,03/31/2016 23:38:00,3320,773,145,Mies van der Rohe Way & Chestnut St,212,Orleans St & Ohio St,Subscriber,Male,1988
9,9080542,03/31/2016 23:22:00,03/31/2016 23:30:00,208,463,90,Millennium Park,174,Canal St & Madison St,Subscriber,Male,1986
10,9080541,03/31/2016 23:22:00,03/31/2016 23:32:00,2241,645,149,Calumet Ave & 33rd St,280,Morgan St & 31st St,Subscriber,Male,1980
11,9080540,03/31/2016 23:16:00,03/31/2016 23:37:00,3464,1253,47,State St & Kinzie St,303,Broadway & Cornelia Ave,Subscriber,Male,1980
12,9080539,03/31/2016 23:17:00,03/31/2016 23:30:00,4303,814,328,Ellis Ave & 58th St,200,MLK Jr Dr & 47th St,Subscriber,Male,1964
13,9080538,03/31/2016 23:14:00,03/31/2016 23:18:00,489,264,133,Kingsbury St & Kinzie St,47,State St & Kinzie St,Subscriber,Male,1991
14,9080536,03/31/2016 23:11:00,03/31/2016 23:16:00,3773,307,310,Damen Ave & Charleston St,213,Leavitt St & North Ave,Subscriber,Male,1990
15,9080535,03/31/2016 23:11:00,03/31/2016 23:14:00,3610,228,67,Sheffield Ave & Fullerton Ave,190,Southport Ave & Wrightwood Ave,Subscriber,Male,1995
16,9080534,03/31/2016 23:09:00,03/31/2016 23:13:00,399,215,67,Sheffield Ave & Fullerton Ave,13,Wilton Ave & Diversey Pkwy,Subscriber,Male,1989
17,9080533,03/31/2016 23:08:00,03/31/2016 23:13:00,2954,256,127,Lincoln Ave & Fullerton Ave,302,Sheffield Ave & Wrightwood Ave,Subscriber,Male,1993
18,9080532,03/31/2016 23:08:00,03/31/2016 23:19:00,1554,668,364,Larrabee St & Oak St,225,Halsted St & Dickens Ave,Subscriber,Female,1984
19,9080531,03/31/2016 23:07:00,03/31/2016 23:18:00,1759,650,31,Franklin St & Chicago Ave,210,Ashland Ave & Division St,Subscriber,Male,1990
20,9080529,03/31/2016 23:07:00,03/31/2016 23:12:00,4389,303,174,Canal St & Madison St,44,State St & Randolph St,Subscriber,Male,1977
21,9080528,03/31/2016 23:06:00,03/31/2016 23:19:00,4034,749,157,Lake Shore Dr & Wellington Ave,256,Broadway & Sheridan Rd,Subscriber,Male,1989
22,9080527,03/31/2016 23:04:00,03/31/2016 23:31:00,1750,1648,460,Clark St & Bryn Mawr Ave,334,Lake Shore Dr & Belmont Ave,Subscriber,Male,1969
23,9080526,03/31/2016 23:04:00,03/31/2016 23:32:00,1638,1648,505,Winchester Ave & Elston Ave,505,Winchester Ave & Elston Ave,Customer,NaN,-1
24,9080525,03/31/2016 23:04:00,03/31/2016 23:06:00,4204,130,131,Lincoln Ave & Belmont Ave,153,Southport Ave & Wellington Ave,Subscriber,Male,1991
25,9080524,03/31/2016 23:03:00,03/31/2016 23:08:00,4383,341,482,Campbell Ave & Montrose Ave,476,Kedzie Ave & Leland Ave,Subscriber,Male,1971
26,9080523,03/31/2016 23:02:00,03/31/2016 23:22:00,2241,1165,420,Ellis Ave & 55th St,149,Calumet Ave & 33rd St,Subscriber,Male,1980
27,9080522,03/31/2016 22:59:00,03/31/2016 23:01:00,3441,128,66,Clinton St & Lake St,164,Franklin St & Lake St,Subscriber,Male,1984
28,9080521,03/31/2016 22:59:00,03/31/2016 23:02:00,3439,198,259,California Ave & Francis Pl,276,California Ave & North Ave,Subscriber,Male,1974
29,9080520,03/31/2016 22:57:00,03/31/2016 23:05:00,3280,492,5,State St & Harrison St,98,LaSalle St & Washington St,Subscriber,Male,1992

In [23]:
trips_2016.info()

<class 'pandas.core.frame.DataFrame'>

Int64Index: 3595383 entries, 0 to 683831

Data columns (total 12 columns):

 #   Column             Dtype

---  ------             -----

 0   trip_id            int64

 1   start_time         object

 2   end_time           object

 3   bikeid             int64

 4   tripduration       int64

 5   from_station_id    int64

 6   from_station_name  object

 7   to_station_id      int64

 8   to_station_name    object

 9   usertype           object

 10  gender             object

 11  birthyear          int32

dtypes: int32(1), int64(5), object(6)

memory usage: 342.9+ MB

In [21]:
trips_2016.to_csv('trips_2016.csv', index=False)

The code used for this year will be used for all the years unless I find problems with the data.